Cms/marketing archives
unswwit/website-v2 pull request #29
Opened 2022-07-18 11:04 UTC by justneocity

Merged marketing archives into contentful. Note: used development access token rather than preview (this ensures only published items are displayed, excluding draft) -> might need to change this for the other cms tables too.

2022-07-18 13:20 UTC, joanna209 requested changes
A couple of things to address and some comments: 
- Please make a slack post for this ticket
- Some of the refactoring has caused issues with filtering, I've highlighted specific parts where these issues have occurred
- Write up some tests in the `__tests__` folder to check that we're getting the marketing data successfully and in the right order

2022-07-18 13:20 UTC, joanna209 commented on frontend/pages/media/marketing.js
> +        picture.category.includes(selectedCategory)
Is there a reason why we're removing the split here? For marketing archives, there is usually more than one category

2022-07-18 13:20 UTC, joanna209 commented on frontend/pages/media/marketing.js
> +    const tempContent = humps.camelizeKeys(res);
Is there a reason why the year filtering methods (e.g. reverse() and filter() were removed for `tempContent`? Seems to be causing issues with the timeline

2022-07-23 14:33 UTC, justneocity commented on frontend/pages/media/marketing.js
> +    console.log(res);
done

2022-09-24 15:19 UTC, joanna209 requested changes

2022-09-24 15:19 UTC, joanna209 commented on frontend/lib/Api.js
> +export async function loadMarketingArchives() {
Delete `Api.js`

2022-09-24 15:19 UTC, joanna209 commented on frontend/pages/media/marketing.js
> +                          date={content.fields.date}
Dates should be formatted in DD/MM/YYYY format. Make sure to write tests!

2022-09-24 15:19 UTC, joanna209 commented on frontend/pages/about/our-team.js
> +    const fetchDataPromises = [fetchSubcom(subcommittee), fetchExecs(execs)];
Why was this changed?

2022-09-24 15:19 UTC, joanna209 commented on frontend/pages/media/marketing.js
> +    setLoading(true);
Look into reimplementing the loading element for the timeline - it seems to be removed :(

2022-09-27 15:45 UTC, Eddyyyh commented on frontend/pages/about/our-team.js
> +    const fetchDataPromises = [fetchSubcom(subcommittee), fetchExecs(execs)];
Prettier did that ^

2022-10-04 17:12 UTC, joanna209 approved these changes

2022-10-04 17:12 UTC, merged